"""
Lexy AI - Dashboard Thoughts Widget.

Displays the most recent autonomous thoughts generated by the
``autonomous_thinking`` plugin.  Subscribes to the
``core.autonomous_thought`` event and caches the last N entries in memory
so the widget always has something to show, even between refresh cycles.

``refresh_interval`` is 0 because updates are push-only:  each new thought
is broadcast via WebSocket by the thinking plugin itself.  The dashboard
polls ``get_data()`` only on initial load or reconnect.
"""

from __future__ import annotations

import time
from collections import deque
from datetime import datetime
from typing import Any

from lexy_core.utils.logging import get_logger

from .base_widget import BaseWidget

log = get_logger(module="widget.thoughts")

_MAX_CACHED: int = 10


class ThoughtsWidget(BaseWidget):
    """Recent autonomous thoughts (push-only, event-driven)."""

    widget_id: str = "thoughts"
    title: str = "Gedanken"
    default_size: tuple[int, int] = (3, 2)
    refresh_interval: float = 0.0  # push-only via event subscription

    def __init__(self, api: Any) -> None:
        super().__init__(api)
        self._cache: deque[dict[str, Any]] = deque(maxlen=_MAX_CACHED)
        self._subscribed: bool = False

    # ─── Event subscription ─────────────────────────────────────────

    def subscribe(self) -> None:
        """
        Subscribe to ``core.autonomous_thought``.

        Called once by the DashboardPlugin after widget instantiation,
        **not** from ``__init__``, so the EventBus is guaranteed to be
        wired up.
        """
        if not self._subscribed:
            self._api.on_event(
                "core.autonomous_thought", self._on_thought
            )
            self._subscribed = True
            log.debug("widget.thoughts.subscribed")

    def _on_thought(self, event: Any) -> None:
        """Cache incoming autonomous thoughts.

        The EventBus delivers an ``Event`` object (with ``.data`` payload),
        not a plain dict; tolerate both for robustness.
        """
        if isinstance(event, dict):
            data = event
        else:
            data = getattr(event, "data", None) or {}
        entry: dict[str, Any] = {
            "mode": str(data.get("mode", "unknown")),
            "text": str(data.get("text", "")),
            "at": datetime.now().strftime("%H:%M"),
            "unix": time.time(),
        }
        self._cache.append(entry)

    # ─── Widget data ────────────────────────────────────────────────

    async def get_data(self) -> dict[str, Any]:
        """Return cached thoughts (newest first)."""
        # Pruefen ob das Thinking-Plugin aktiviert ist. Wir lesen
        # ``_thinking_active`` (die benutzer-sichtbare "Loop läuft"-Flag),
        # NICHT ``_enabled`` — letzteres ist ein Framework-Flag aus
        # ``BasePlugin`` und sagt nur, dass der Plugin-Lifecycle
        # abgeschlossen ist.
        thinking_plugin = self._api.get_plugin("autonomous_thinking")
        enabled: bool = False
        if thinking_plugin is not None:
            enabled = bool(getattr(thinking_plugin, "_thinking_active", False))

        thoughts = list(reversed(self._cache))

        return {
            "thoughts": thoughts,
            "count": len(thoughts),
            "enabled": enabled,
        }
